// Common given and family names per country, for the seed (SEED-3). Japanese names are romaji;
// "neutral" given names are used for non-binary people and are common for any gender in that country.
import type { Country } from '@acme/shared';

export type NameLists = { female: string[]; male: string[]; neutral: string[]; last: string[] };

export const NAMES: Record<Country, NameLists> = {
  US: {
    female: [
      'Emily', 'Sarah', 'Jessica', 'Ashley', 'Jennifer', 'Amanda', 'Elizabeth', 'Megan', 'Lauren', 'Rachel',
      'Hannah', 'Olivia', 'Emma', 'Madison', 'Abigail', 'Grace', 'Chloe', 'Natalie', 'Samantha', 'Victoria',
      'Rebecca', 'Katherine', 'Michelle', 'Stephanie', 'Nicole', 'Heather', 'Melissa', 'Danielle', 'Brittany', 'Kayla',
      'Sophia', 'Isabella', 'Ava', 'Mia', 'Charlotte', 'Amelia', 'Harper', 'Evelyn', 'Ella', 'Lily',
      'Zoe', 'Nora', 'Claire', 'Audrey', 'Leah', 'Maya', 'Aaliyah', 'Gabriela', 'Mariana', 'Jasmine',
      'Destiny', 'Brianna', 'Andrea', 'Monica', 'Erin', 'Kelly', 'Allison', 'Courtney', 'Vanessa', 'Diana',
    ],
    male: [
      'James', 'Michael', 'Robert', 'John', 'David', 'William', 'Richard', 'Joseph', 'Thomas', 'Christopher',
      'Daniel', 'Matthew', 'Anthony', 'Mark', 'Andrew', 'Joshua', 'Kevin', 'Brian', 'Ryan', 'Jacob',
      'Nicholas', 'Eric', 'Jonathan', 'Justin', 'Brandon', 'Tyler', 'Aaron', 'Adam', 'Nathan', 'Zachary',
      'Ethan', 'Noah', 'Liam', 'Mason', 'Logan', 'Lucas', 'Elijah', 'Benjamin', 'Samuel', 'Henry',
      'Caleb', 'Owen', 'Isaac', 'Gabriel', 'Dylan', 'Luis', 'Carlos', 'Marcus', 'Jamal', 'Darius',
      'Trevor', 'Kyle', 'Sean', 'Patrick', 'Gregory', 'Scott', 'Travis', 'Derek', 'Cody', 'Austin',
    ],
    neutral: [
      'Alex', 'Taylor', 'Casey', 'Riley', 'Morgan', 'Jamie', 'Avery', 'Quinn', 'Rowan', 'Sam',
      'Charlie', 'Skyler', 'Emerson', 'Finley', 'Hayden', 'Parker', 'Reese', 'Sage', 'Dakota', 'Peyton',
    ],
    last: [
      'Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Garcia', 'Miller', 'Davis', 'Rodriguez', 'Martinez',
      'Hernandez', 'Lopez', 'Gonzalez', 'Wilson', 'Anderson', 'Thomas', 'Taylor', 'Moore', 'Jackson', 'Martin',
      'Lee', 'Perez', 'Thompson', 'White', 'Harris', 'Sanchez', 'Clark', 'Ramirez', 'Lewis', 'Robinson',
      'Walker', 'Young', 'Allen', 'King', 'Wright', 'Scott', 'Torres', 'Nguyen', 'Hill', 'Flores',
      'Green', 'Adams', 'Nelson', 'Baker', 'Hall', 'Rivera', 'Campbell', 'Mitchell', 'Carter', 'Roberts',
      'Gomez', 'Phillips', 'Evans', 'Turner', 'Diaz', 'Parker', 'Cruz', 'Edwards', 'Collins', 'Reyes',
      'Stewart', 'Morris', 'Morales', 'Murphy', 'Cook', 'Rogers', 'Gutierrez', 'Ortiz', 'Morgan', 'Cooper',
      'Peterson', 'Bailey', 'Reed', 'Kelly', 'Howard', 'Ramos', 'Kim', 'Cox', 'Ward', 'Richardson',
      'Watson', 'Brooks', 'Chavez', 'Wood', 'James', 'Bennett', 'Gray', 'Mendoza', 'Ruiz', 'Hughes',
      'Price', 'Alvarez', 'Castillo', 'Sanders', 'Patel', 'Myers', 'Long', 'Ross', 'Foster', 'Jimenez',
    ],
  },
  IN: {
    female: [
      'Priya', 'Ananya', 'Aishwarya', 'Divya', 'Kavya', 'Pooja', 'Sneha', 'Neha', 'Shreya', 'Anjali',
      'Deepika', 'Meera', 'Lakshmi', 'Swati', 'Nisha', 'Ritu', 'Sunita', 'Kavitha', 'Lavanya', 'Revathi',
      'Pavithra', 'Harini', 'Nandini', 'Sowmya', 'Bhavana', 'Aparna', 'Madhuri', 'Rashmi', 'Sapna', 'Komal',
      'Isha', 'Tanvi', 'Riya', 'Aditi', 'Sakshi', 'Megha', 'Payal', 'Ankita', 'Shruti', 'Vidya',
      'Gayatri', 'Padma', 'Sangeetha', 'Keerthana', 'Amrita', 'Debjani', 'Sharmila', 'Moumita', 'Tanushree', 'Ishita',
      'Fatima', 'Ayesha', 'Zoya', 'Sana', 'Mehreen', 'Gurleen', 'Simran', 'Navya', 'Saanvi', 'Anika',
    ],
    male: [
      'Rahul', 'Amit', 'Rohit', 'Arjun', 'Vikram', 'Sanjay', 'Rajesh', 'Suresh', 'Ramesh', 'Anil',
      'Arun', 'Karthik', 'Vijay', 'Manoj', 'Deepak', 'Nikhil', 'Siddharth', 'Aditya', 'Varun', 'Abhishek',
      'Ankit', 'Gaurav', 'Pranav', 'Harish', 'Venkatesh', 'Srinivas', 'Prakash', 'Ganesh', 'Mahesh', 'Naveen',
      'Sandeep', 'Vivek', 'Ajay', 'Ashok', 'Mohan', 'Balaji', 'Senthil', 'Murali', 'Krishna', 'Raghav',
      'Aarav', 'Vihaan', 'Ishaan', 'Kabir', 'Arnav', 'Dhruv', 'Yash', 'Tushar', 'Saurabh', 'Kunal',
      'Imran', 'Faisal', 'Arif', 'Sameer', 'Manish', 'Rakesh', 'Hitesh', 'Sourav', 'Debashish', 'Anirban',
    ],
    neutral: [
      'Kiran', 'Jyoti', 'Shashi', 'Suman', 'Navneet', 'Manpreet', 'Ashwini', 'Anupam', 'Prabhjot', 'Kamal',
      'Shubham', 'Santosh', 'Sukhjeet', 'Amarjeet', 'Swaroop', 'Rajni',
    ],
    last: [
      'Sharma', 'Verma', 'Gupta', 'Singh', 'Kumar', 'Patel', 'Shah', 'Mehta', 'Joshi', 'Desai',
      'Iyer', 'Iyengar', 'Rao', 'Reddy', 'Naidu', 'Nair', 'Menon', 'Pillai', 'Krishnan', 'Subramanian',
      'Raman', 'Srinivasan', 'Venkataraman', 'Natarajan', 'Chandrasekhar', 'Banerjee', 'Chatterjee', 'Mukherjee', 'Bose', 'Das',
      'Ghosh', 'Sen', 'Dutta', 'Roy', 'Chakraborty', 'Kulkarni', 'Deshpande', 'Patil', 'Jadhav', 'Pawar',
      'Shinde', 'Gokhale', 'Bhat', 'Hegde', 'Shetty', 'Kamath', 'Pai', 'Agarwal', 'Bansal', 'Malhotra',
      'Kapoor', 'Khanna', 'Chopra', 'Arora', 'Sethi', 'Bhatia', 'Saxena', 'Srivastava', 'Mishra', 'Tiwari',
      'Pandey', 'Dubey', 'Chauhan', 'Rathore', 'Yadav', 'Thakur', 'Gill', 'Sandhu', 'Dhillon', 'Grewal',
      'Khan', 'Ahmed', 'Siddiqui', 'Qureshi', 'Ansari', 'Sheikh', 'Fernandes', "D'Souza", 'Pereira', 'Rodrigues',
      'Mathew', 'Thomas', 'Varghese', 'Kurian', 'Chandran', 'Gopalan', 'Balakrishnan', 'Raghavan', 'Ranganathan', 'Sundaram',
      'Trivedi', 'Pandya', 'Bhatt', 'Vyas', 'Parikh', 'Choudhary', 'Mahajan', 'Sinha', 'Jha', 'Prasad',
    ],
  },
  GB: {
    female: [
      'Olivia', 'Amelia', 'Isla', 'Ava', 'Emily', 'Sophie', 'Grace', 'Lily', 'Ella', 'Freya',
      'Charlotte', 'Poppy', 'Evie', 'Jessica', 'Lucy', 'Hannah', 'Chloe', 'Megan', 'Holly', 'Katie',
      'Sarah', 'Rebecca', 'Laura', 'Emma', 'Gemma', 'Claire', 'Helen', 'Rachel', 'Joanne', 'Nicola',
      'Victoria', 'Eleanor', 'Harriet', 'Imogen', 'Phoebe', 'Rosie', 'Alice', 'Florence', 'Matilda', 'Daisy',
      'Niamh', 'Siobhan', 'Aoife', 'Eilidh', 'Morag', 'Catriona', 'Bethan', 'Cerys', 'Seren', 'Ffion',
      'Priya', 'Aisha', 'Zara', 'Amira', 'Leah', 'Abigail', 'Jade', 'Kirsty', 'Lauren', 'Natasha',
    ],
    male: [
      'Oliver', 'George', 'Harry', 'Jack', 'Jacob', 'Noah', 'Toby', 'Thomas', 'Oscar', 'William',
      'James', 'Henry', 'Leo', 'Alfie', 'Joshua', 'Freddie', 'Archie', 'Ethan', 'Isaac', 'Alexander',
      'Daniel', 'Matthew', 'Samuel', 'Benjamin', 'Joseph', 'Edward', 'Lewis', 'Callum', 'Ryan', 'Liam',
      'Connor', 'Max', 'Ross', 'Euan', 'Fraser', 'Angus', 'Rhys', 'Dylan', 'Owain', 'Gareth',
      'Ciaran', 'Declan', 'Patrick', 'Sean', 'Mohammed', 'Arjun', 'Hamza', 'Aaron', 'Nathan', 'Luke',
      'Stephen', 'Paul', 'Mark', 'Richard', 'David', 'Andrew', 'Simon', 'Neil', 'Graham', 'Ian',
    ],
    neutral: [
      'Alex', 'Charlie', 'Sam', 'Jamie', 'Robin', 'Frankie', 'Jo', 'Morgan', 'Rowan', 'Billie',
      'Jesse', 'Kit', 'Sasha', 'Remi', 'Ellis', 'Harley', 'Toni', 'Lou',
    ],
    last: [
      'Smith', 'Jones', 'Taylor', 'Brown', 'Williams', 'Wilson', 'Johnson', 'Davies', 'Patel', 'Robinson',
      'Wright', 'Thompson', 'Evans', 'Walker', 'White', 'Roberts', 'Green', 'Hall', 'Thomas', 'Clarke',
      'Jackson', 'Wood', 'Harris', 'Edwards', 'Turner', 'Martin', 'Cooper', 'Hill', 'Ward', 'Hughes',
      'Moore', 'Clark', 'King', 'Harrison', 'Lewis', 'Baker', 'Lee', 'Allen', 'Morris', 'Khan',
      'Scott', 'Watson', 'Davis', 'Parker', 'James', 'Bennett', 'Young', 'Phillips', 'Richardson', 'Mitchell',
      'Bailey', 'Carter', 'Cook', 'Singh', 'Shaw', 'Bell', 'Collins', 'Morgan', 'Kelly', 'Begum',
      'Miller', 'Cox', 'Hussain', 'Marshall', 'Simpson', 'Price', 'Anderson', 'Adams', 'Wilkinson', 'Ali',
      'Ahmed', 'Foster', 'Ellis', 'Murphy', 'Chapman', 'Mason', 'Gray', 'Richards', 'Webb', 'Griffiths',
      'Hunt', 'Palmer', 'Campbell', 'Holmes', 'Mills', 'Rogers', 'Barnes', 'Knight', 'Matthews', 'Barker',
      'MacDonald', 'Stewart', 'Murray', 'Reid', 'Fraser', "O'Brien", "O'Connor", 'Byrne', 'Llewellyn', 'Pritchard',
    ],
  },
  DE: {
    female: [
      'Anna', 'Lena', 'Laura', 'Julia', 'Sarah', 'Lisa', 'Katharina', 'Johanna', 'Sophie', 'Marie',
      'Hannah', 'Lea', 'Leonie', 'Emma', 'Mia', 'Clara', 'Charlotte', 'Paula', 'Greta', 'Frieda',
      'Sabine', 'Petra', 'Claudia', 'Andrea', 'Susanne', 'Stefanie', 'Nicole', 'Kerstin', 'Birgit', 'Heike',
      'Franziska', 'Christina', 'Jana', 'Anja', 'Melanie', 'Tanja', 'Katrin', 'Daniela', 'Miriam', 'Nadine',
      'Ines', 'Ute', 'Monika', 'Ulrike', 'Gisela', 'Elif', 'Ayşe', 'Zeynep', 'Natalia', 'Agnieszka',
      'Magdalena', 'Theresa', 'Antonia', 'Helena', 'Luisa', 'Amelie', 'Mila', 'Ida', 'Pia', 'Svenja',
    ],
    male: [
      'Thomas', 'Michael', 'Andreas', 'Stefan', 'Christian', 'Markus', 'Matthias', 'Tobias', 'Florian', 'Sebastian',
      'Alexander', 'Daniel', 'Jan', 'Lukas', 'Felix', 'Jonas', 'Leon', 'Paul', 'Maximilian', 'Finn',
      'Elias', 'Ben', 'Moritz', 'Niklas', 'Philipp', 'Julian', 'Simon', 'David', 'Fabian', 'Dominik',
      'Jürgen', 'Klaus', 'Wolfgang', 'Uwe', 'Frank', 'Ralf', 'Holger', 'Dirk', 'Sven', 'Jens',
      'Torsten', 'Kai', 'Lars', 'Björn', 'Mehmet', 'Emre', 'Can', 'Piotr', 'Tomasz', 'Johannes',
      'Benedikt', 'Konstantin', 'Valentin', 'Henrik', 'Malte', 'Ole', 'Timo', 'Patrick', 'Marcel', 'Oliver',
    ],
    neutral: [
      'Kim', 'Alex', 'Robin', 'Sascha', 'Mika', 'Toni', 'Charlie', 'Luca', 'Jona', 'Eike',
      'Nikola', 'Chris', 'Sam', 'Jo', 'Maxi', 'Jule',
    ],
    last: [
      'Müller', 'Schmidt', 'Schneider', 'Fischer', 'Weber', 'Meyer', 'Wagner', 'Becker', 'Schulz', 'Hoffmann',
      'Schäfer', 'Koch', 'Bauer', 'Richter', 'Klein', 'Wolf', 'Schröder', 'Neumann', 'Schwarz', 'Zimmermann',
      'Braun', 'Krüger', 'Hofmann', 'Hartmann', 'Lange', 'Schmitt', 'Werner', 'Schmitz', 'Krause', 'Meier',
      'Lehmann', 'Schmid', 'Schulze', 'Maier', 'Köhler', 'Herrmann', 'König', 'Walter', 'Mayer', 'Huber',
      'Kaiser', 'Fuchs', 'Peters', 'Lang', 'Scholz', 'Möller', 'Weiß', 'Jung', 'Hahn', 'Schubert',
      'Vogel', 'Friedrich', 'Keller', 'Günther', 'Frank', 'Berger', 'Winkler', 'Roth', 'Beck', 'Lorenz',
      'Baumann', 'Franke', 'Albrecht', 'Schuster', 'Simon', 'Ludwig', 'Böhm', 'Winter', 'Kraus', 'Martin',
      'Schumacher', 'Krämer', 'Vogt', 'Stein', 'Jäger', 'Otto', 'Sommer', 'Groß', 'Seidel', 'Heinrich',
      'Brandt', 'Haas', 'Schreiber', 'Graf', 'Schulte', 'Dietrich', 'Ziegler', 'Kuhn', 'Kühn', 'Pohl',
      'Engel', 'Horn', 'Busch', 'Bergmann', 'Thomas', 'Voigt', 'Sauer', 'Arnold', 'Wolff', 'Yılmaz',
    ],
  },
  BR: {
    female: [
      'Maria', 'Ana', 'Juliana', 'Fernanda', 'Mariana', 'Camila', 'Beatriz', 'Larissa', 'Gabriela', 'Amanda',
      'Bruna', 'Letícia', 'Patrícia', 'Aline', 'Vanessa', 'Carolina', 'Isabela', 'Luana', 'Natália', 'Rafaela',
      'Daniela', 'Renata', 'Tatiane', 'Priscila', 'Débora', 'Cristina', 'Luciana', 'Adriana', 'Simone', 'Sandra',
      'Alice', 'Helena', 'Laura', 'Valentina', 'Sophia', 'Manuela', 'Lívia', 'Giovanna', 'Yasmin', 'Clara',
      'Raquel', 'Thaís', 'Jéssica', 'Bianca', 'Eduarda', 'Lorena', 'Mirella', 'Viviane', 'Fabiana', 'Elaine',
      'Joana', 'Cecília', 'Heloísa', 'Rebeca', 'Sabrina', 'Caroline', 'Michele', 'Paula', 'Márcia', 'Rosana',
    ],
    male: [
      'João', 'José', 'Pedro', 'Lucas', 'Gabriel', 'Matheus', 'Rafael', 'Felipe', 'Gustavo', 'Bruno',
      'Thiago', 'Rodrigo', 'Diego', 'Leonardo', 'Eduardo', 'Marcelo', 'Fernando', 'André', 'Ricardo', 'Carlos',
      'Paulo', 'Luiz', 'Antônio', 'Francisco', 'Marcos', 'Daniel', 'Vinícius', 'Caio', 'Henrique', 'Samuel',
      'Miguel', 'Arthur', 'Heitor', 'Davi', 'Bernardo', 'Enzo', 'Lorenzo', 'Théo', 'Murilo', 'Otávio',
      'Leandro', 'Fábio', 'Renato', 'Sérgio', 'Alexandre', 'Márcio', 'Júlio', 'Roberto', 'Wesley', 'Igor',
      'Caetano', 'Raul', 'Vítor', 'Douglas', 'Guilherme', 'Hugo', 'Nicolas', 'Kauã', 'Cauê', 'Wellington',
    ],
    neutral: [
      'Alex', 'Ariel', 'Dani', 'Cris', 'Gabi', 'Rafa', 'Val', 'Juraci', 'Darci', 'Iraci',
      'Jaci', 'Sam', 'Noá', 'Luca', 'Andrea', 'Dominique',
    ],
    last: [
      'Silva', 'Santos', 'Oliveira', 'Souza', 'Rodrigues', 'Ferreira', 'Alves', 'Pereira', 'Lima', 'Gomes',
      'Costa', 'Ribeiro', 'Martins', 'Carvalho', 'Almeida', 'Lopes', 'Soares', 'Fernandes', 'Vieira', 'Barbosa',
      'Rocha', 'Dias', 'Nascimento', 'Andrade', 'Moreira', 'Nunes', 'Marques', 'Machado', 'Mendes', 'Freitas',
      'Cardoso', 'Ramos', 'Gonçalves', 'Santana', 'Teixeira', 'Araújo', 'Pinto', 'Correia', 'Cavalcanti', 'Monteiro',
      'Moura', 'Batista', 'Azevedo', 'Campos', 'Rezende', 'Barros', 'Castro', 'Duarte', 'Farias', 'Miranda',
      'Melo', 'Nogueira', 'Pacheco', 'Pires', 'Queiroz', 'Sales', 'Siqueira', 'Tavares', 'Vasconcelos', 'Xavier',
      'Brito', 'Coelho', 'Cunha', 'Fonseca', 'Guimarães', 'Lacerda', 'Leite', 'Macedo', 'Magalhães', 'Medeiros',
      'Morais', 'Neves', 'Peixoto', 'Prado', 'Rangel', 'Sampaio', 'Toledo', 'Valente', 'Bezerra', 'Bittencourt',
      'Borges', 'Brandão', 'Cabral', 'Camargo', 'Cordeiro', 'Couto', 'Dantas', 'Esteves', 'Falcão', 'Figueiredo',
      'Frade', 'Galvão', 'Holanda', 'Jardim', 'Lins', 'Maciel', 'Matos', 'Paiva', 'Quintana', 'Sá',
    ],
  },
  JP: {
    female: [
      'Yui', 'Hina', 'Sakura', 'Yuna', 'Aoi', 'Mei', 'Rin', 'Himari', 'Mio', 'Saki',
      'Yuka', 'Ayaka', 'Haruka', 'Misaki', 'Nanami', 'Mai', 'Asuka', 'Kanako', 'Erika', 'Yoko',
      'Keiko', 'Naoko', 'Tomoko', 'Megumi', 'Yumiko', 'Kumiko', 'Akiko', 'Noriko', 'Sachiko', 'Emi',
      'Ayumi', 'Chika', 'Eri', 'Kaori', 'Mayumi', 'Natsumi', 'Rie', 'Sayaka', 'Shiori', 'Yuko',
      'Miyu', 'Kokona', 'Tsumugi', 'Riko', 'Honoka', 'Akane', 'Momoka', 'Nozomi', 'Maki', 'Junko',
    ],
    male: [
      'Haruto', 'Sota', 'Yuto', 'Ren', 'Riku', 'Minato', 'Hayato', 'Sora', 'Kaito', 'Takumi',
      'Daiki', 'Shota', 'Kenta', 'Yuki', 'Takeshi', 'Hiroshi', 'Kenji', 'Takashi', 'Satoshi', 'Kazuki',
      'Ryota', 'Naoki', 'Tomoya', 'Yusuke', 'Daisuke', 'Shinji', 'Koji', 'Masato', 'Tetsuya', 'Hiroki',
      'Akira', 'Kei', 'Ryo', 'Sho', 'Taiga', 'Tsubasa', 'Yamato', 'Haruki', 'Itsuki', 'Asahi',
      'Kosuke', 'Makoto', 'Noboru', 'Osamu', 'Shun', 'Tatsuya', 'Yoshiaki', 'Yuichi', 'Junichi', 'Masahiro',
    ],
    neutral: [
      'Hikaru', 'Kaoru', 'Nao', 'Chihiro', 'Shinobu', 'Masumi', 'Natsuki', 'Izumi', 'Michiru', 'Mizuki',
      'Haru', 'Tomomi', 'Jun', 'Rei', 'Yu', 'Aki',
    ],
    last: [
      'Sato', 'Suzuki', 'Takahashi', 'Tanaka', 'Watanabe', 'Ito', 'Yamamoto', 'Nakamura', 'Kobayashi', 'Kato',
      'Yoshida', 'Yamada', 'Sasaki', 'Yamaguchi', 'Matsumoto', 'Inoue', 'Kimura', 'Hayashi', 'Shimizu', 'Yamazaki',
      'Mori', 'Abe', 'Ikeda', 'Hashimoto', 'Yamashita', 'Ishikawa', 'Nakajima', 'Maeda', 'Fujita', 'Ogawa',
      'Goto', 'Okada', 'Hasegawa', 'Murakami', 'Kondo', 'Ishii', 'Saito', 'Sakamoto', 'Endo', 'Aoki',
      'Fujii', 'Nishimura', 'Fukuda', 'Ota', 'Miura', 'Fujiwara', 'Okamoto', 'Matsuda', 'Nakagawa', 'Nakano',
      'Harada', 'Ono', 'Tamura', 'Takeuchi', 'Kaneko', 'Wada', 'Nakayama', 'Ishida', 'Ueda', 'Morita',
      'Hara', 'Shibata', 'Sakai', 'Kudo', 'Yokoyama', 'Miyazaki', 'Miyamoto', 'Uchida', 'Takagi', 'Ando',
      'Taniguchi', 'Ohno', 'Maruyama', 'Imai', 'Takada', 'Fujimoto', 'Takeda', 'Murata', 'Ueno', 'Sugiyama',
    ],
  },
};
